// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuGgODa2M8FC6ba7cItEZYnLhfHNM2vKU',
    appId: '1:291731181987:android:9474e5f6661eda5d200a16',
    messagingSenderId: '291731181987',
    projectId: 'quizapp-11478',
    storageBucket: 'quizapp-11478.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVhGjNDev8X4AIuoFRjTzke1eUZCfPR24',
    appId: '1:291731181987:ios:a7fd1fec650e00eb200a16',
    messagingSenderId: '291731181987',
    projectId: 'quizapp-11478',
    storageBucket: 'quizapp-11478.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVhGjNDev8X4AIuoFRjTzke1eUZCfPR24',
    appId: '1:291731181987:ios:a7fd1fec650e00eb200a16',
    messagingSenderId: '291731181987',
    projectId: 'quizapp-11478',
    storageBucket: 'quizapp-11478.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmF7dx4acJLJlY1R5x9_ZOmSxpD0iKNpg',
    appId: '1:291731181987:web:50057d3c5b35ac6e200a16',
    messagingSenderId: '291731181987',
    projectId: 'quizapp-11478',
    authDomain: 'quizapp-11478.firebaseapp.com',
    storageBucket: 'quizapp-11478.firebasestorage.app',
    measurementId: 'G-7XDXFYQ8GE',
  );
}
